builds:
  - binary: mediumautopost
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: mediumautopost
    homepage: "https://github.com/SharokhAtaie/Sub-Enumeration"
    tap:
      owner: SharokhAtaie
      name: subenumeration
    commit_author:
      name: sharokh
      email: ataiesharokh@gmail.com

checksum:
  name_template: 'checksums.txt'